### ISSUE TITLE
Column objects

### ISSUE THREAD

**Issue by katjabercic** [DiscreteZOO/DiscreteZOO-sage#6]
Make column objects for all columns in the database for better user experience. Example:
diam = C("diameter")

**Comment by nbasic** [comment]
The name of the object should be the column name, not something completely different.

**Comment by jaanos** [comment]
Done. The objects can be imported from `graphzoo.class.fields`, and should also include objects from the superclass. So, for now we have the objects in `graphzoo.cvt.fields`, which include the objects from `graphzoo.zoograph.fields`.
